/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import sun.awt.image.GifImageDecoder;

/**
 *
 * @author usuario
 */
public class ventanaAhorcado extends javax.swing.JFrame {
    
    String palabraOculta = "CETYS";
    int contadorFallos = 0;
    int aciertos = 0;
    
    /**
     * Creates new form ventanaAhorcado
     */
    public ventanaAhorcado() {
        initComponents();
    }
    
    private void chequeaBoton(JButton boton){
        chequeaLetra(boton.getText());
        boton.setEnabled(false);
    }
    
    private void chequeaLetra(String letra){
        String auxiliar = palabraGuiones.getText();
        boolean perder = false;
       
        if (palabraOculta.contains(letra)){
            //la letra si que está, tengo que quitar el guión bajo 
            //y ponerla en su posición
            //si usas indexOf te subo la nota
            for (int i=0; i<palabraOculta.length(); i++){
                if(palabraOculta.charAt(i) == letra.charAt(0)){
                    System.out.println(i);
                    auxiliar = auxiliar.substring(0, 2*i) + letra + auxiliar.substring(2*i + 1);
                    
                }
                if (aciertos==palabraOculta.length()){
                    System.out.println("Has acertado todas!! Eres un winner :)");
                    dibujaImagen2();
                }
            }
            palabraGuiones.setText(auxiliar);
        }
        
        if (contadorFallos==6){
            System.out.println("Has perdido :( mua mua");
        }
        else{
            //la letra no está y hay que aumentar el contador de fallos
            //y cambiar la imagen del ahorcado
            contadorFallos++;
            dibujaImagen();
        }
        
        //que el juego detecte si la partida ha terminado 
        //porque has ganado
        //o porque has perdido
    }
    
    private void dibujaImagen(){
        String nombreImagen = "";
        switch (contadorFallos){//switch instrucción que tienen todos los lenguajes de programación
            case 0: nombreImagen = "/imagenes/ahorcado_0.png"; break;
            case 1: nombreImagen = "/imagenes/ahorcado_1.png"; break;
            case 2: nombreImagen = "/imagenes/ahorcado_2.png"; break;
            case 3: nombreImagen = "/imagenes/ahorcado_3.png"; break;
            case 4: nombreImagen = "/imagenes/ahorcado_4.png"; break;
            case 5: nombreImagen = "/imagenes/ahorcado_5.png"; break;
            case 6 : nombreImagen = "/imagenes/ahorcado_fin.jpeg"; break;
        }
        //cargar la imágen correspondiente en el jLable del imagenahorcado
        ImageIcon miImagen = new ImageIcon(
        new ImageIcon(getClass().getResource(nombreImagen)).getImage()
                .getScaledInstance(imagenAhorcado.getWidth(), 
                        imagenAhorcado.getHeight(), Image.SCALE_DEFAULT)
        );
        imagenAhorcado.setIcon(miImagen);
    }
    private void dibujaImagen2(){

        String nombreImagen2 = "";
        switch (aciertos){
            case 0: nombreImagen2 = "/imagenes/acertasteTodo.png"; break;
            default : nombreImagen2 = "/imagenes/acertasteTodo.png"; break;
        }
        //cargar la imágen correspondiente en el jLable del imagenahorcado
        ImageIcon miImagen = new ImageIcon(
        new ImageIcon(getClass().getResource(nombreImagen2)).getImage()
                .getScaledInstance(imagenAhorcado.getWidth(), 
                        imagenAhorcado.getHeight(), Image.SCALE_DEFAULT)
        );
        imagenAhorcado.setIcon(miImagen);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palabraGuiones = new javax.swing.JLabel();
        imagenAhorcado = new javax.swing.JLabel();
        letra_A = new javax.swing.JButton();
        letra_B = new javax.swing.JButton();
        letra_C = new javax.swing.JButton();
        letra_D = new javax.swing.JButton();
        letra_E = new javax.swing.JButton();
        letra_F = new javax.swing.JButton();
        letra_G = new javax.swing.JButton();
        letra_H = new javax.swing.JButton();
        letra_I = new javax.swing.JButton();
        letra_J = new javax.swing.JButton();
        letra_K = new javax.swing.JButton();
        letra_L = new javax.swing.JButton();
        letra_M = new javax.swing.JButton();
        letra_N = new javax.swing.JButton();
        letra_Ñ = new javax.swing.JButton();
        letra_O = new javax.swing.JButton();
        letra_P = new javax.swing.JButton();
        letra_Q = new javax.swing.JButton();
        letra_R = new javax.swing.JButton();
        letra_S = new javax.swing.JButton();
        letra_T = new javax.swing.JButton();
        letra_U = new javax.swing.JButton();
        letra_V = new javax.swing.JButton();
        letra_W = new javax.swing.JButton();
        letra = new javax.swing.JButton();
        letra_X = new javax.swing.JButton();
        letra_Y = new javax.swing.JButton();
        letra_Z = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(490, 737));

        palabraGuiones.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        palabraGuiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabraGuiones.setText("_ _ _ _ _");
        palabraGuiones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        letra_A.setText("A");
        letra_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_AActionPerformed(evt);
            }
        });

        letra_B.setText("B");
        letra_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_BActionPerformed(evt);
            }
        });

        letra_C.setText("C");
        letra_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_CActionPerformed(evt);
            }
        });

        letra_D.setText("D");
        letra_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_DActionPerformed(evt);
            }
        });

        letra_E.setText("E");
        letra_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_EActionPerformed(evt);
            }
        });

        letra_F.setText("F");
        letra_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_FActionPerformed(evt);
            }
        });

        letra_G.setText("G");
        letra_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_GActionPerformed(evt);
            }
        });

        letra_H.setText("H");
        letra_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_HActionPerformed(evt);
            }
        });

        letra_I.setText("I");
        letra_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_IActionPerformed(evt);
            }
        });

        letra_J.setText("J");
        letra_J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_JActionPerformed(evt);
            }
        });

        letra_K.setText("K");
        letra_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_KActionPerformed(evt);
            }
        });

        letra_L.setText("L");
        letra_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_LActionPerformed(evt);
            }
        });

        letra_M.setText("M");
        letra_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_MActionPerformed(evt);
            }
        });

        letra_N.setText("N");
        letra_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_NActionPerformed(evt);
            }
        });

        letra_Ñ.setText("Ñ");
        letra_Ñ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_ÑActionPerformed(evt);
            }
        });

        letra_O.setText("O");
        letra_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_OActionPerformed(evt);
            }
        });

        letra_P.setText("P");
        letra_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_PActionPerformed(evt);
            }
        });

        letra_Q.setText("Q");
        letra_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_QActionPerformed(evt);
            }
        });

        letra_R.setText("R");
        letra_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_RActionPerformed(evt);
            }
        });

        letra_S.setText("S");
        letra_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_SActionPerformed(evt);
            }
        });

        letra_T.setText("T");
        letra_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_TActionPerformed(evt);
            }
        });

        letra_U.setText("U");
        letra_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_UActionPerformed(evt);
            }
        });

        letra_V.setText("V");
        letra_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_VActionPerformed(evt);
            }
        });

        letra_W.setText("W");
        letra_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_WActionPerformed(evt);
            }
        });

        letra.setEnabled(false);
        letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraActionPerformed(evt);
            }
        });

        letra_X.setText("X");
        letra_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_XActionPerformed(evt);
            }
        });

        letra_Y.setText("Y");
        letra_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_YActionPerformed(evt);
            }
        });

        letra_Z.setText("Z");
        letra_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_ZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palabraGuiones, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letra_A, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_B, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_E, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_F, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_G, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letra_H, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_I, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_J, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_K, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_L, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_M, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_N, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letra_Ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_O, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_P, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_R, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letra_U, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_V, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_W, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_X, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(imagenAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(palabraGuiones, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imagenAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra_A, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_B, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_E, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_F, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_G, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra_H, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_I, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_J, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_K, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_L, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_M, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_N, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra_Ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_O, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_P, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_R, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra_U, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_V, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_W, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_X, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_AActionPerformed
       chequeaBoton((JButton)evt.getSource());//evt es el evento //te dice quién ha realizado el evento(el boton exacto al hacer clic en el)//a esto se le llama castear
    }//GEN-LAST:event_letra_AActionPerformed

    private void letra_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_BActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_BActionPerformed

    private void letra_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_CActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_CActionPerformed

    private void letra_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_DActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_DActionPerformed

    private void letra_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_EActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_EActionPerformed

    private void letra_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_FActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_FActionPerformed

    private void letra_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_GActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_GActionPerformed

    private void letra_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_HActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_HActionPerformed

    private void letra_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_IActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_IActionPerformed

    private void letra_JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_JActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_JActionPerformed

    private void letra_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_KActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_KActionPerformed

    private void letra_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_LActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_LActionPerformed

    private void letra_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_MActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_MActionPerformed

    private void letra_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_NActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_NActionPerformed

    private void letra_ÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_ÑActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_ÑActionPerformed

    private void letra_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_OActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_OActionPerformed

    private void letra_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_PActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_PActionPerformed

    private void letra_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_QActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_QActionPerformed

    private void letra_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_RActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_RActionPerformed

    private void letra_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_SActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_SActionPerformed

    private void letra_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_TActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_TActionPerformed

    private void letra_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_UActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_UActionPerformed

    private void letra_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_VActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_VActionPerformed

    private void letra_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_WActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_WActionPerformed

    private void letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letraActionPerformed

    private void letra_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_XActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_XActionPerformed

    private void letra_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_YActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_YActionPerformed

    private void letra_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_ZActionPerformed
       chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra_ZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenAhorcado;
    private javax.swing.JButton letra;
    private javax.swing.JButton letra_A;
    private javax.swing.JButton letra_B;
    private javax.swing.JButton letra_C;
    private javax.swing.JButton letra_D;
    private javax.swing.JButton letra_E;
    private javax.swing.JButton letra_F;
    private javax.swing.JButton letra_G;
    private javax.swing.JButton letra_H;
    private javax.swing.JButton letra_I;
    private javax.swing.JButton letra_J;
    private javax.swing.JButton letra_K;
    private javax.swing.JButton letra_L;
    private javax.swing.JButton letra_M;
    private javax.swing.JButton letra_N;
    private javax.swing.JButton letra_O;
    private javax.swing.JButton letra_P;
    private javax.swing.JButton letra_Q;
    private javax.swing.JButton letra_R;
    private javax.swing.JButton letra_S;
    private javax.swing.JButton letra_T;
    private javax.swing.JButton letra_U;
    private javax.swing.JButton letra_V;
    private javax.swing.JButton letra_W;
    private javax.swing.JButton letra_X;
    private javax.swing.JButton letra_Y;
    private javax.swing.JButton letra_Z;
    private javax.swing.JButton letra_Ñ;
    private javax.swing.JLabel palabraGuiones;
    // End of variables declaration//GEN-END:variables
}
